//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLyra.Dota2.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dota2Entities : DbContext
    {
        public Dota2Entities()
            : base("name=Dota2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbilityType> AbilityType { get; set; }
        public virtual DbSet<Attributes> Attributes { get; set; }
        public virtual DbSet<DamageType> DamageType { get; set; }
        public virtual DbSet<Hero> Hero { get; set; }
        public virtual DbSet<HeroPortraits> HeroPortraits { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<SkillAbilityTypes> SkillAbilityTypes { get; set; }
        public virtual DbSet<SkillImage> SkillImage { get; set; }
        public virtual DbSet<TargetAffectedType> TargetAffectedType { get; set; }
    }
}
