//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLyra.Dota2.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillAbilityTypes
    {
        public int ID { get; set; }
        public int SkillId { get; set; }
        public int AbilityTypeId { get; set; }
    
        public virtual AbilityType AbilityType { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
