//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLyra.Dota2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attributes
    {
        public string ID { get; set; }
        public string Agility { get; set; }
        public string Intelligence { get; set; }
        public string Strength { get; set; }
        public string Damage { get; set; }
        public string MoveSpeed { get; set; }
        public string Armor { get; set; }
    }
}
