//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Dota2Model", "FK_Skill_0", "AbilityType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GLyra.Dota2.AbilityType), "Skill", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GLyra.Dota2.Skill), true)]
[assembly: EdmRelationshipAttribute("Dota2Model", "FK_Skill_2", "DamageType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GLyra.Dota2.DamageType), "Skill", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GLyra.Dota2.Skill), true)]
[assembly: EdmRelationshipAttribute("Dota2Model", "FK_Hero_0", "Skill", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GLyra.Dota2.Skill), "Hero", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GLyra.Dota2.Hero), true)]
[assembly: EdmRelationshipAttribute("Dota2Model", "FK_Skill_1", "TargetAffectedType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GLyra.Dota2.TargetAffectedType), "Skill", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GLyra.Dota2.Skill), true)]

#endregion

namespace GLyra.Dota2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Dota2Entities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Dota2Entities1 object using the connection string found in the 'Dota2Entities1' section of the application configuration file.
        /// </summary>
        public Dota2Entities1() : base("name=Dota2Entities1", "Dota2Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Dota2Entities1 object.
        /// </summary>
        public Dota2Entities1(string connectionString) : base(connectionString, "Dota2Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Dota2Entities1 object.
        /// </summary>
        public Dota2Entities1(EntityConnection connection) : base(connection, "Dota2Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AbilityType> AbilityType
        {
            get
            {
                if ((_AbilityType == null))
                {
                    _AbilityType = base.CreateObjectSet<AbilityType>("AbilityType");
                }
                return _AbilityType;
            }
        }
        private ObjectSet<AbilityType> _AbilityType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Attributes> Attributes
        {
            get
            {
                if ((_Attributes == null))
                {
                    _Attributes = base.CreateObjectSet<Attributes>("Attributes");
                }
                return _Attributes;
            }
        }
        private ObjectSet<Attributes> _Attributes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DamageType> DamageType
        {
            get
            {
                if ((_DamageType == null))
                {
                    _DamageType = base.CreateObjectSet<DamageType>("DamageType");
                }
                return _DamageType;
            }
        }
        private ObjectSet<DamageType> _DamageType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hero> Hero
        {
            get
            {
                if ((_Hero == null))
                {
                    _Hero = base.CreateObjectSet<Hero>("Hero");
                }
                return _Hero;
            }
        }
        private ObjectSet<Hero> _Hero;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Skill> Skill
        {
            get
            {
                if ((_Skill == null))
                {
                    _Skill = base.CreateObjectSet<Skill>("Skill");
                }
                return _Skill;
            }
        }
        private ObjectSet<Skill> _Skill;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TargetAffectedType> TargetAffectedType
        {
            get
            {
                if ((_TargetAffectedType == null))
                {
                    _TargetAffectedType = base.CreateObjectSet<TargetAffectedType>("TargetAffectedType");
                }
                return _TargetAffectedType;
            }
        }
        private ObjectSet<TargetAffectedType> _TargetAffectedType;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AbilityType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAbilityType(AbilityType abilityType)
        {
            base.AddObject("AbilityType", abilityType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Attributes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAttributes(Attributes attributes)
        {
            base.AddObject("Attributes", attributes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DamageType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDamageType(DamageType damageType)
        {
            base.AddObject("DamageType", damageType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hero EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHero(Hero hero)
        {
            base.AddObject("Hero", hero);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Skill EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSkill(Skill skill)
        {
            base.AddObject("Skill", skill);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TargetAffectedType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTargetAffectedType(TargetAffectedType targetAffectedType)
        {
            base.AddObject("TargetAffectedType", targetAffectedType);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dota2Model", Name="AbilityType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AbilityType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AbilityType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static AbilityType CreateAbilityType(global::System.Int32 id, global::System.String name)
        {
            AbilityType abilityType = new AbilityType();
            abilityType.ID = id;
            abilityType.Name = name;
            return abilityType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dota2Model", "FK_Skill_0", "Skill")]
        public EntityCollection<Skill> Skill
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Skill>("Dota2Model.FK_Skill_0", "Skill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Skill>("Dota2Model.FK_Skill_0", "Skill", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dota2Model", Name="Attributes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Attributes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Attributes object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="agility">Initial value of the Agility property.</param>
        /// <param name="intelligence">Initial value of the Intelligence property.</param>
        /// <param name="strength">Initial value of the Strength property.</param>
        /// <param name="damage">Initial value of the Damage property.</param>
        /// <param name="moveSpeed">Initial value of the MoveSpeed property.</param>
        /// <param name="armor">Initial value of the Armor property.</param>
        public static Attributes CreateAttributes(global::System.String id, global::System.String agility, global::System.String intelligence, global::System.String strength, global::System.String damage, global::System.String moveSpeed, global::System.String armor)
        {
            Attributes attributes = new Attributes();
            attributes.ID = id;
            attributes.Agility = agility;
            attributes.Intelligence = intelligence;
            attributes.Strength = strength;
            attributes.Damage = damage;
            attributes.MoveSpeed = moveSpeed;
            attributes.Armor = armor;
            return attributes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Agility
        {
            get
            {
                return _Agility;
            }
            set
            {
                if (_Agility != value)
                {
                    OnAgilityChanging(value);
                    ReportPropertyChanging("Agility");
                    _Agility = StructuralObject.SetValidValue(value, false, "Agility");
                    ReportPropertyChanged("Agility");
                    OnAgilityChanged();
                }
            }
        }
        private global::System.String _Agility;
        partial void OnAgilityChanging(global::System.String value);
        partial void OnAgilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Intelligence
        {
            get
            {
                return _Intelligence;
            }
            set
            {
                if (_Intelligence != value)
                {
                    OnIntelligenceChanging(value);
                    ReportPropertyChanging("Intelligence");
                    _Intelligence = StructuralObject.SetValidValue(value, false, "Intelligence");
                    ReportPropertyChanged("Intelligence");
                    OnIntelligenceChanged();
                }
            }
        }
        private global::System.String _Intelligence;
        partial void OnIntelligenceChanging(global::System.String value);
        partial void OnIntelligenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Strength
        {
            get
            {
                return _Strength;
            }
            set
            {
                if (_Strength != value)
                {
                    OnStrengthChanging(value);
                    ReportPropertyChanging("Strength");
                    _Strength = StructuralObject.SetValidValue(value, false, "Strength");
                    ReportPropertyChanged("Strength");
                    OnStrengthChanged();
                }
            }
        }
        private global::System.String _Strength;
        partial void OnStrengthChanging(global::System.String value);
        partial void OnStrengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Damage
        {
            get
            {
                return _Damage;
            }
            set
            {
                if (_Damage != value)
                {
                    OnDamageChanging(value);
                    ReportPropertyChanging("Damage");
                    _Damage = StructuralObject.SetValidValue(value, false, "Damage");
                    ReportPropertyChanged("Damage");
                    OnDamageChanged();
                }
            }
        }
        private global::System.String _Damage;
        partial void OnDamageChanging(global::System.String value);
        partial void OnDamageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MoveSpeed
        {
            get
            {
                return _MoveSpeed;
            }
            set
            {
                if (_MoveSpeed != value)
                {
                    OnMoveSpeedChanging(value);
                    ReportPropertyChanging("MoveSpeed");
                    _MoveSpeed = StructuralObject.SetValidValue(value, false, "MoveSpeed");
                    ReportPropertyChanged("MoveSpeed");
                    OnMoveSpeedChanged();
                }
            }
        }
        private global::System.String _MoveSpeed;
        partial void OnMoveSpeedChanging(global::System.String value);
        partial void OnMoveSpeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Armor
        {
            get
            {
                return _Armor;
            }
            set
            {
                if (_Armor != value)
                {
                    OnArmorChanging(value);
                    ReportPropertyChanging("Armor");
                    _Armor = StructuralObject.SetValidValue(value, false, "Armor");
                    ReportPropertyChanged("Armor");
                    OnArmorChanged();
                }
            }
        }
        private global::System.String _Armor;
        partial void OnArmorChanging(global::System.String value);
        partial void OnArmorChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dota2Model", Name="DamageType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DamageType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DamageType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static DamageType CreateDamageType(global::System.Int32 id, global::System.String name)
        {
            DamageType damageType = new DamageType();
            damageType.ID = id;
            damageType.Name = name;
            return damageType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dota2Model", "FK_Skill_2", "Skill")]
        public EntityCollection<Skill> Skill
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Skill>("Dota2Model.FK_Skill_2", "Skill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Skill>("Dota2Model.FK_Skill_2", "Skill", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dota2Model", Name="Hero")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hero : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hero object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="skillsId">Initial value of the SkillsId property.</param>
        /// <param name="attributesId">Initial value of the AttributesId property.</param>
        /// <param name="biography">Initial value of the Biography property.</param>
        /// <param name="heroPortraitsId">Initial value of the HeroPortraitsId property.</param>
        /// <param name="attributes_ID">Initial value of the Attributes_ID property.</param>
        public static Hero CreateHero(global::System.Int32 id, global::System.String name, global::System.Int32 skillsId, global::System.Int32 attributesId, global::System.String biography, global::System.Int32 heroPortraitsId, global::System.String attributes_ID)
        {
            Hero hero = new Hero();
            hero.ID = id;
            hero.Name = name;
            hero.SkillsId = skillsId;
            hero.AttributesId = attributesId;
            hero.Biography = biography;
            hero.HeroPortraitsId = heroPortraitsId;
            hero.Attributes_ID = attributes_ID;
            return hero;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SkillsId
        {
            get
            {
                return _SkillsId;
            }
            set
            {
                OnSkillsIdChanging(value);
                ReportPropertyChanging("SkillsId");
                _SkillsId = StructuralObject.SetValidValue(value, "SkillsId");
                ReportPropertyChanged("SkillsId");
                OnSkillsIdChanged();
            }
        }
        private global::System.Int32 _SkillsId;
        partial void OnSkillsIdChanging(global::System.Int32 value);
        partial void OnSkillsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttributesId
        {
            get
            {
                return _AttributesId;
            }
            set
            {
                OnAttributesIdChanging(value);
                ReportPropertyChanging("AttributesId");
                _AttributesId = StructuralObject.SetValidValue(value, "AttributesId");
                ReportPropertyChanged("AttributesId");
                OnAttributesIdChanged();
            }
        }
        private global::System.Int32 _AttributesId;
        partial void OnAttributesIdChanging(global::System.Int32 value);
        partial void OnAttributesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Biography
        {
            get
            {
                return _Biography;
            }
            set
            {
                OnBiographyChanging(value);
                ReportPropertyChanging("Biography");
                _Biography = StructuralObject.SetValidValue(value, false, "Biography");
                ReportPropertyChanged("Biography");
                OnBiographyChanged();
            }
        }
        private global::System.String _Biography;
        partial void OnBiographyChanging(global::System.String value);
        partial void OnBiographyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeroPortraitsId
        {
            get
            {
                return _HeroPortraitsId;
            }
            set
            {
                OnHeroPortraitsIdChanging(value);
                ReportPropertyChanging("HeroPortraitsId");
                _HeroPortraitsId = StructuralObject.SetValidValue(value, "HeroPortraitsId");
                ReportPropertyChanged("HeroPortraitsId");
                OnHeroPortraitsIdChanged();
            }
        }
        private global::System.Int32 _HeroPortraitsId;
        partial void OnHeroPortraitsIdChanging(global::System.Int32 value);
        partial void OnHeroPortraitsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Attributes_ID
        {
            get
            {
                return _Attributes_ID;
            }
            set
            {
                OnAttributes_IDChanging(value);
                ReportPropertyChanging("Attributes_ID");
                _Attributes_ID = StructuralObject.SetValidValue(value, false, "Attributes_ID");
                ReportPropertyChanged("Attributes_ID");
                OnAttributes_IDChanged();
            }
        }
        private global::System.String _Attributes_ID;
        partial void OnAttributes_IDChanging(global::System.String value);
        partial void OnAttributes_IDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dota2Model", "FK_Hero_0", "Skill")]
        public Skill Skill
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Skill>("Dota2Model.FK_Hero_0", "Skill").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Skill>("Dota2Model.FK_Hero_0", "Skill").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Skill> SkillReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Skill>("Dota2Model.FK_Hero_0", "Skill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Skill>("Dota2Model.FK_Hero_0", "Skill", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dota2Model", Name="Skill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Skill : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Skill object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="abilityTypeId">Initial value of the AbilityTypeId property.</param>
        /// <param name="imageId">Initial value of the ImageId property.</param>
        public static Skill CreateSkill(global::System.Int32 id, global::System.String name, global::System.String description, global::System.Int32 abilityTypeId, global::System.Int32 imageId)
        {
            Skill skill = new Skill();
            skill.ID = id;
            skill.Name = name;
            skill.Description = description;
            skill.AbilityTypeId = abilityTypeId;
            skill.ImageId = imageId;
            return skill;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ManaCostLv1
        {
            get
            {
                return _ManaCostLv1;
            }
            set
            {
                OnManaCostLv1Changing(value);
                ReportPropertyChanging("ManaCostLv1");
                _ManaCostLv1 = StructuralObject.SetValidValue(value, "ManaCostLv1");
                ReportPropertyChanged("ManaCostLv1");
                OnManaCostLv1Changed();
            }
        }
        private Nullable<global::System.Int32> _ManaCostLv1;
        partial void OnManaCostLv1Changing(Nullable<global::System.Int32> value);
        partial void OnManaCostLv1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ManaCostLv2
        {
            get
            {
                return _ManaCostLv2;
            }
            set
            {
                OnManaCostLv2Changing(value);
                ReportPropertyChanging("ManaCostLv2");
                _ManaCostLv2 = StructuralObject.SetValidValue(value, "ManaCostLv2");
                ReportPropertyChanged("ManaCostLv2");
                OnManaCostLv2Changed();
            }
        }
        private Nullable<global::System.Int32> _ManaCostLv2;
        partial void OnManaCostLv2Changing(Nullable<global::System.Int32> value);
        partial void OnManaCostLv2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ManaCostLv3
        {
            get
            {
                return _ManaCostLv3;
            }
            set
            {
                OnManaCostLv3Changing(value);
                ReportPropertyChanging("ManaCostLv3");
                _ManaCostLv3 = StructuralObject.SetValidValue(value, "ManaCostLv3");
                ReportPropertyChanged("ManaCostLv3");
                OnManaCostLv3Changed();
            }
        }
        private Nullable<global::System.Int32> _ManaCostLv3;
        partial void OnManaCostLv3Changing(Nullable<global::System.Int32> value);
        partial void OnManaCostLv3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ManaCostLv4
        {
            get
            {
                return _ManaCostLv4;
            }
            set
            {
                OnManaCostLv4Changing(value);
                ReportPropertyChanging("ManaCostLv4");
                _ManaCostLv4 = StructuralObject.SetValidValue(value, "ManaCostLv4");
                ReportPropertyChanged("ManaCostLv4");
                OnManaCostLv4Changed();
            }
        }
        private Nullable<global::System.Int32> _ManaCostLv4;
        partial void OnManaCostLv4Changing(Nullable<global::System.Int32> value);
        partial void OnManaCostLv4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CoolDownLv1
        {
            get
            {
                return _CoolDownLv1;
            }
            set
            {
                OnCoolDownLv1Changing(value);
                ReportPropertyChanging("CoolDownLv1");
                _CoolDownLv1 = StructuralObject.SetValidValue(value, "CoolDownLv1");
                ReportPropertyChanged("CoolDownLv1");
                OnCoolDownLv1Changed();
            }
        }
        private Nullable<global::System.Int32> _CoolDownLv1;
        partial void OnCoolDownLv1Changing(Nullable<global::System.Int32> value);
        partial void OnCoolDownLv1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CoolDownLv2
        {
            get
            {
                return _CoolDownLv2;
            }
            set
            {
                OnCoolDownLv2Changing(value);
                ReportPropertyChanging("CoolDownLv2");
                _CoolDownLv2 = StructuralObject.SetValidValue(value, "CoolDownLv2");
                ReportPropertyChanged("CoolDownLv2");
                OnCoolDownLv2Changed();
            }
        }
        private Nullable<global::System.Int32> _CoolDownLv2;
        partial void OnCoolDownLv2Changing(Nullable<global::System.Int32> value);
        partial void OnCoolDownLv2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CoolDownLv3
        {
            get
            {
                return _CoolDownLv3;
            }
            set
            {
                OnCoolDownLv3Changing(value);
                ReportPropertyChanging("CoolDownLv3");
                _CoolDownLv3 = StructuralObject.SetValidValue(value, "CoolDownLv3");
                ReportPropertyChanged("CoolDownLv3");
                OnCoolDownLv3Changed();
            }
        }
        private Nullable<global::System.Int32> _CoolDownLv3;
        partial void OnCoolDownLv3Changing(Nullable<global::System.Int32> value);
        partial void OnCoolDownLv3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CoolDownLv4
        {
            get
            {
                return _CoolDownLv4;
            }
            set
            {
                OnCoolDownLv4Changing(value);
                ReportPropertyChanging("CoolDownLv4");
                _CoolDownLv4 = StructuralObject.SetValidValue(value, "CoolDownLv4");
                ReportPropertyChanged("CoolDownLv4");
                OnCoolDownLv4Changed();
            }
        }
        private Nullable<global::System.Int32> _CoolDownLv4;
        partial void OnCoolDownLv4Changing(Nullable<global::System.Int32> value);
        partial void OnCoolDownLv4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AbilityTypeId
        {
            get
            {
                return _AbilityTypeId;
            }
            set
            {
                OnAbilityTypeIdChanging(value);
                ReportPropertyChanging("AbilityTypeId");
                _AbilityTypeId = StructuralObject.SetValidValue(value, "AbilityTypeId");
                ReportPropertyChanged("AbilityTypeId");
                OnAbilityTypeIdChanged();
            }
        }
        private global::System.Int32 _AbilityTypeId;
        partial void OnAbilityTypeIdChanging(global::System.Int32 value);
        partial void OnAbilityTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TargetAffectedTypeId
        {
            get
            {
                return _TargetAffectedTypeId;
            }
            set
            {
                OnTargetAffectedTypeIdChanging(value);
                ReportPropertyChanging("TargetAffectedTypeId");
                _TargetAffectedTypeId = StructuralObject.SetValidValue(value, "TargetAffectedTypeId");
                ReportPropertyChanged("TargetAffectedTypeId");
                OnTargetAffectedTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TargetAffectedTypeId;
        partial void OnTargetAffectedTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnTargetAffectedTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DamageTypeId
        {
            get
            {
                return _DamageTypeId;
            }
            set
            {
                OnDamageTypeIdChanging(value);
                ReportPropertyChanging("DamageTypeId");
                _DamageTypeId = StructuralObject.SetValidValue(value, "DamageTypeId");
                ReportPropertyChanged("DamageTypeId");
                OnDamageTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DamageTypeId;
        partial void OnDamageTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnDamageTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageId
        {
            get
            {
                return _ImageId;
            }
            set
            {
                OnImageIdChanging(value);
                ReportPropertyChanging("ImageId");
                _ImageId = StructuralObject.SetValidValue(value, "ImageId");
                ReportPropertyChanged("ImageId");
                OnImageIdChanged();
            }
        }
        private global::System.Int32 _ImageId;
        partial void OnImageIdChanging(global::System.Int32 value);
        partial void OnImageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VideoUrl
        {
            get
            {
                return _VideoUrl;
            }
            set
            {
                OnVideoUrlChanging(value);
                ReportPropertyChanging("VideoUrl");
                _VideoUrl = StructuralObject.SetValidValue(value, true, "VideoUrl");
                ReportPropertyChanged("VideoUrl");
                OnVideoUrlChanged();
            }
        }
        private global::System.String _VideoUrl;
        partial void OnVideoUrlChanging(global::System.String value);
        partial void OnVideoUrlChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dota2Model", "FK_Skill_0", "AbilityType")]
        public AbilityType AbilityType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AbilityType>("Dota2Model.FK_Skill_0", "AbilityType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AbilityType>("Dota2Model.FK_Skill_0", "AbilityType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AbilityType> AbilityTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AbilityType>("Dota2Model.FK_Skill_0", "AbilityType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AbilityType>("Dota2Model.FK_Skill_0", "AbilityType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dota2Model", "FK_Skill_2", "DamageType")]
        public DamageType DamageType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DamageType>("Dota2Model.FK_Skill_2", "DamageType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DamageType>("Dota2Model.FK_Skill_2", "DamageType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DamageType> DamageTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DamageType>("Dota2Model.FK_Skill_2", "DamageType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DamageType>("Dota2Model.FK_Skill_2", "DamageType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dota2Model", "FK_Hero_0", "Hero")]
        public EntityCollection<Hero> Hero
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Hero>("Dota2Model.FK_Hero_0", "Hero");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Hero>("Dota2Model.FK_Hero_0", "Hero", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dota2Model", "FK_Skill_1", "TargetAffectedType")]
        public TargetAffectedType TargetAffectedType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TargetAffectedType>("Dota2Model.FK_Skill_1", "TargetAffectedType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TargetAffectedType>("Dota2Model.FK_Skill_1", "TargetAffectedType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TargetAffectedType> TargetAffectedTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TargetAffectedType>("Dota2Model.FK_Skill_1", "TargetAffectedType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TargetAffectedType>("Dota2Model.FK_Skill_1", "TargetAffectedType", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Dota2Model", Name="TargetAffectedType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TargetAffectedType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TargetAffectedType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static TargetAffectedType CreateTargetAffectedType(global::System.Int32 id, global::System.String name)
        {
            TargetAffectedType targetAffectedType = new TargetAffectedType();
            targetAffectedType.ID = id;
            targetAffectedType.Name = name;
            return targetAffectedType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Dota2Model", "FK_Skill_1", "Skill")]
        public EntityCollection<Skill> Skill
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Skill>("Dota2Model.FK_Skill_1", "Skill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Skill>("Dota2Model.FK_Skill_1", "Skill", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
