//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLyra.Dota2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dota2Entities1 : DbContext
    {
        public Dota2Entities1()
            : base("name=Dota2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AbilityType> AbilityType { get; set; }
        public DbSet<Attributes> Attributes { get; set; }
        public DbSet<DamageType> DamageType { get; set; }
        public DbSet<Hero> Hero { get; set; }
        public DbSet<Skill> Skill { get; set; }
        public DbSet<TargetAffectedType> TargetAffectedType { get; set; }
    }
}
