//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLyra.Dota2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public Hero()
        {
            this.HeroPortraits = new HashSet<HeroPortraits>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int SkillsId { get; set; }
        public int AttributesId { get; set; }
        public string Biography { get; set; }
        public int HeroPortraitsId { get; set; }
    
        public virtual Attributes Attributes { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual ICollection<HeroPortraits> HeroPortraits { get; set; }
    }
}
